### ISSUE TITLE
show links to images

### ISSUE THREAD

**Issue by ghost** [auioc/banciyuan-archive#1]
### Description

please add the links to images instead of md5 values

### Environment

https://p3-bcy-sign.bcyimg.com/banciyuan/065c2a37c6c54d008a24686c3e5a44f6~tplv-banciyuan-abig.image?x-expires=1704510690&x-signature=ZX%2FwzFsIQUOMgNAMewjBC4eQfnw%3D

### Reproduction steps

https://p3-bcy-sign.bcyimg.com/banciyuan/065c2a37c6c54d008a24686c3e5a44f6~tplv-banciyuan-abig.image?x-expires=1704510690&x-signature=ZX%2FwzFsIQUOMgNAMewjBC4eQfnw%3D

**Comment by lainio24** [comment]
半次元已停服，图片链接会过期，
不可能再提供图片链接。

所有带有有效的文件大小信息的图片在 [PCC-Studio](https://www.pccstudio.com/) 处均有存储（[README](https://github.com/auioc/banciyuan-archive#%E8%87%B4%E8%B0%A2)），但目前我们还未找到合适的分发图片的方式（[README](https://github.com/auioc/banciyuan-archive#%E5%BE%85%E5%8A%9E%E4%BA%8B%E9%A1%B9)），如果您有合适的方式，请另行发起议题。

**Comment by ghost** [comment]
全部传到ipfs上，用户做种？
